apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1 # Usually = 3 on prod
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: amigoscode/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube # Different values: kube, docker. it means it will use the application-kube.yml file
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification
