apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  labels:
    app: fraud
spec:
  replicas: 1 # Usually = 3 on prod
  template:
    metadata:
      name: fraud
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: amigoscode/fraud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube # Different values: kube, docker. it means it will use the application-kube.yml file
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraud
